# Permalinks
permalink:           pretty

# Setup
title:               Abhilash John Philip
tagline:             Product Manager from New Delhi.
url:                 https://abhilashjp.github.io/theme2/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Abhilash John Philip
  url:               https://twitter.com/abhilashjp
  email:             abhilashjohn07@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/abhilashjp/theme2
google_analytics:    UA-85047587-1
twitter:             abhilashjp
github:              abhilashjp           

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
